### ISSUE TITLE
error message when installing Postcalendar on 1.4.4-dev

### ISSUE THREAD

**Issue by MrMontesa** [craigh/PostCalendar#112]
When testing 1.4.4-dev I tried installing PostCalendar and came accross the follwoing error:

`Error found in composer file of PostCalendar (PostCalendar) in property "extra": The property extra is required.`

Had a chat with Guite about it in another core ticket (https://github.com/zikula/core/issues/3194) and he supposed that this might be a Postcalendar issue that the composer file is incomplete.

**Comment by MrMontesa** [comment]
Tried editing composer.json myself but was not able to fill all required fields.

```
    "extra": {
        "zikula": {
        }
    }
```

Then it complained about missing: extra.zikula.class which I cant predict.

**Comment by craigh** [comment]
@guite

**Comment by craigh** [comment]
Postcalendar is a legacy module and shouldn't have a composer file at all. However it should still install and maybe @guite s changes in the core have broken this.  But is SHOULD work in the corr

**Comment by Guite** [comment]
The composer file is invalid because several required elements are not contained. Easiest solution is removing the file.

**Comment by craigh** [comment]
I think the core should handle this better by dialing the validation of composer files for non-bundle type modules.

closing this as it is a core issue
