### ISSUE TITLE
Display of DateTime objects are always in English

### ISSUE THREAD

**Issue by craigh** [craigh/PostCalendar#48]
Dates, while formatted according to the selected "order" are not translated.

e.g.
14 March 2012
is displayed when using the German language pack where it should be
14 Mär 2012

I believe the answer lies here:
http://www.php.net/manual/en/class.intldateformatter.php

but will take some work.

Ironically, the jQuery plugin seems to be somewhat localized, so after a date is selected in the datepicker, the field is temporarily displayed correctly, but then reverts to English upon submission of the form.

**Comment by trichers** [comment]
I installed PostCalendar 8.0.3 / Zikula 1.3.10 and have the Problem, that the Month and Weekday-Name are allways in english. I tried to add to the templates (that´s how it works in Clip-templates), but doesn´t work:
{php}
$loc_de = setlocale (LC_ALL, 'de_DE.UTF-8');
{/php}

Do you have an idea?

**Comment by craigh** [comment]
no idea. sorry. @ccandreva ?
